### ISSUE TITLE
New way to display work item associations in details view

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#644]
_From @sanbornsen on January 7, 2017 6:0_

**Reference:** 1608E102/1608E063
``` Note: This is an extension of story #306 ``` 
# Description
As a user, I want to be able to see and drill down into an associated work item details on a work item detail view.

# Functional Acceptance Criteria
1. The user can see a list of associated/linked work items.
2. Associated work item entries are presented with id, title and the type of association in a way that it does not clutter the interface.
3. The user can directly go to the detail view of an associated work item from the list of associated work items. (**Note:** according to #298, the back operation on the drilled down detail view will go back to the previous view, which in this case would be this view).
4. The user can delete associations by clicking on the delete button. Deleting an association requires a confirmation. Deletion of an association removes the entry instantly from the presented list. 
5. UX implementation as defined by the UX team (Workflow, Wireframe).
# Non-functional Acceptance Criteria
1. All updates are done in-place.

# Dependencies
1. Userstory #298  

# Tasks
- [ ] New UX design considering multiple work item link types
- [ ] Expose available workitem link types to link with current item in Work Item API https://github.com/almighty/almighty-core/issues/324
- [ ] Implement UI to support updated work item API with exposed available link types

_Copied from original issue: almighty/almighty-core#639_

**Comment by michaelkleinhenz** [comment]
_From @sanbornsen on January 7, 2017 6:6_

# Questions 
* Can one link type has multiple source types and target types?
* What happens if the reverse name and forward names are same for a link type? I believe in that case all the source and destinations should be same in such kind of link types. For example, for a link type **relates to** where the forward name and backward name is both **relates to**, the source and destination work item types should be same. i.e. **type1, type2 <- relates to -> type1, type2**

**Comment by michaelkleinhenz** [comment]
_From @sanbornsen on January 7, 2017 6:7_

@kwk @aslakknutsen please comment.

**Comment by michaelkleinhenz** [comment]
_From @sanbornsen on January 7, 2017 6:8_

@Mgranfie @mindreeper2420 any update on the new Wireframe / Visuals for linking? Please provide an issue number if you have any in UX.

**Comment by Mgranfie** [comment]
@michaelkleinhenz this was not designed for V1, as at the time it was determined that it was not needed, so this interaction is not in the current WIL designs. We are working on tasks and the solution for drilling down to a WI from a WI may similar and we can look at solving the interaction for both of these scenarios together. @essjaysee ...

**Comment by kwk** [comment]
See also https://github.com/almighty/almighty-core/issues/473 and https://github.com/almighty/almighty-core/pull/602
