### ISSUE TITLE
 Updated Build System for Planner [5]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#645]
# Description
As a developer, I want to have a stable development and deployment environment for the library version of the Planner component.

# Functional Acceptance Criteria
1. The Planner can be built as an integration library/component that can be used by external Angular 2 applications.

# Non-functional Acceptance Criteria
1. There is an easy to setup and use way to code-iterate over the Planner.

**Note:** This story is more about the non-functional criterias. The library build/deployment needs an easy way for developers to do development cycles without dealing with a complex setup. This might be a setup with the platform project running locally, but could also be something like a generic minimal frame, omitting the platform for development of the Planner. So this story will boil down on looking how development is working with the Platform-Planner setup.

_Copied from original issue: almighty/almighty-core#638_

# Tasks
- [x] Implement test integration #694
- [x] Implement build automation #693
- [x] Add debug environment build to build system #692
- [x] Add/evaluate debug environment for developing #691
- [x] Implement library build feature #690
