### ISSUE TITLE
Display Work Item in a Board View [6]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#671]
# Description

As a user, I want to see the current work items in a board view and do operations on them.
# Functional Acceptance Criteria
* The board view is classified based on work item state.
* Work items are displayed in a board view, with title, type, for each list item (work item).
* Only one work item type is displayed on the board view at any one time.
* The user can select the work item type from a dropdown (similar to a filter).
* Each work item will be displayed on a Card (Patternfly Card View)
* Each column of the board view can be scrolled to navigate over all the items.
* The board view page can be scrolled horizontally to view all the columns or for drag and drop.
* UX implementation as defined by the UX team (Workflow, Visual Design).

**Note:** The board view only displays one work item type at any one time because different work item types may hav different valid states and with that, different lane configurations.

# Non-functional Acceptance Criteria
1. The board view is displayed in a efficient way, even when the list has a very large number of entries.

# UX artifacts
https://redhat.invisionapp.com/share/E89O7H3B2#/screens/210499779

# Tasks

- [ ] CORE: Filter by work item states #823
- [ ] UI: Update state columns based on the selected work item type #1029
- [ ] UI: Implement infinite scroll for each column with the filter in board view #1027
- [ ] UX: UX for selecting work item type

**Comment by ldimaggi** [comment]
Will we provide any filtering/sorting on cards in the board?

**Comment by ldimaggi** [comment]
Will we provide any customization of the display of the cards in the board? (summary, verbose)

**Comment by naina-verma** [comment]
Why we are using (+) add work item for every column(todo, inprogress,done) :https://redhat.invisionapp.com/share/E89O7H3B2#/screens/213049305 
Can it be on one place ? As it is same feature repeating many times on one screen .
Any thoughts !!

**Comment by Ritsyy** [comment]
@michaelkleinhenz We need the board view behave same as the work item list for the current user story and not as per a particular iteration?

**Comment by michaelkleinhenz** [comment]
UX: https://redhat.invisionapp.com/share/56AH8F1XM#/screens/221408817
