### ISSUE TITLE
Space Context for Planner [8]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#673]
# Description
As a user, I want to use the Planner in the context of a specific selected space.

# Functional Acceptance Criteria
1. The Planner is aware of the current space context (retrieved from the Platform frame).
2. All actions/operations in the Planner are always performed in the context of the current space.

# Non-functional Acceptance Criteria
None.

*Note*: the selection mechanism/UI facilities for selecting the space are not part of this story.

# Tasks
- [x] Update tests to reflect dynamic URL handling #702
- [x] Setup internal persistence of space context #700
- [x] Implement Bootstrapping of initial context #699
- [x] Implement internal notification system for space context changes #698
- [x] Acquire current space from Platform #697
- [x] Refactor services for the dynamic URL handling #696
- [x] Add dynamic URL handling for core requests #695

**Comment by ldimaggi** [comment]
Will the UI always display the current space for the user?

**Comment by nimishamukherjee** [comment]
Scenario - Planner needs to run independently of Platform.
As a developer, assuming that core has been set-up locally, should the planner create a default project if no project exists and reuse this project subsequently?

**Comment by michaelvirgil** [comment]
@fabric8io/uxd - Please see @ldimaggi question above.

**Comment by Mgranfie** [comment]
I would suggest that it would be better to encourage and guide the user to
start a new collaboration space. We do have a graphic on the landing page
once the user logs in. If just the planner, means no landing page, then we
could prompt them on log in to then create a new collaboration space. This
way they choose their project type ect... name it... we could have a dummy
one in there as an example if this is more what you were asking?

-Monica

**Comment by Mgranfie** [comment]
@ldimaggi Are you asking if the planner will display the space name, with or within the navigation framework that Todd + Pete are establishing? Which use case are you thinking of?
