### ISSUE TITLE
Extend the create modal with a date picker for start and end date input

### ISSUE THREAD

**Issue by sanbornsen** [fabric8io/fabric8-planner#726]
### Description
We'll need a date picker input for the create modal. Date picker will only be visible in case of update. The display of that input field is logical.

### Tasks
- [ ] Create an input field for displaying the date
- [ ] The field should not be editable but clickable
- [ ] If start date and end date is not empty / null it should show the dates in a format
- [ ] Else should show empty field with a placeholder
- [ ] Clicking on the field should open a date picker for a date range
- [ ] Select the date range and save would set the start and end date

### Reference
User story - https://github.com/fabric8io/fabric8-planner/issues/646

**Comment by sanbornsen** [comment]
Planning to use this library - 
https://github.com/onehungrymind/ng2-daterangepicker
