### ISSUE TITLE
Restructure the code to share iteration panel share between list and board

### ISSUE THREAD

**Issue by sanbornsen** [fabric8io/fabric8-planner#735]
### Description
The planner code for work item needs to be restructured. The list module and board module should come under a parent module. The parent module will have the common feature shared by both the views. For example, the iteration panel and the filter bar.

### Tasks
- [x] Make a common parent module
- [x] Configure the routing to access list and board from the parent
- [x] Move details page to the common module
- [x] Move filter bar and feature to the common module

### References
User story - https://github.com/fabric8io/fabric8-planner/issues/647
Blocks - https://github.com/fabric8io/fabric8-planner/issues/708
