### ISSUE TITLE
All views agnostic to used template: Labels [8]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#883]
# Description
As a user, I want to see attribute labels, control values (like dropdown value lists) and UI titles according to my selected process template.

# Functional Acceptance Criteria
1. All labels and other UX strings like list titles are dyamic according to the selected process template.
3. All list values (like dropdown values) are dyamic according to the selected process template.

# Non-functional Acceptance Criteria
None.

**Note:** There are no dynamic forms required for this story, just re-labeling of the forms and controls..

# Related tasks

- [x] UI: [Use titles, descriptions, icons (CSS class names) defined in WIT #997](https://github.com/fabric8io/fabric8-planner/issues/997)
- [x] UI: [Adapt to JSONAPI for WIT #998](https://github.com/fabric8io/fabric8-planner/issues/998)
- [ ] CORE: [Define a space template layout #684](https://github.com/almighty/almighty-core/issues/684)
- [ ] CORE: [Create REST API for Create and List of Space Template #833](https://github.com/almighty/almighty-core/issues/833)
- [ ] CORE: [Validation process for space template #847](https://github.com/almighty/almighty-core/issues/847)
- [x] CORE: [Convert work item type (WIT) REST API to JSONAPI #674](https://github.com/almighty/almighty-core/issues/674)
- [x] CORE: [Augment fields in WIT with name and description field #848](https://github.com/almighty/almighty-core/issues/848)
- [x] CORE: [Augment WIT with icon or CSS class name #916](https://github.com/almighty/almighty-core/issues/916)

**Comment by michaelkleinhenz** [comment]
Question to @mindreeper2420: there are almost no labels in the current application that need to be changed out based on the template. The only one I found was the Quick Add Label ("Add Work Item"), but this could easily be chenged to something neutral, like "Add new..".
Question is: what do we need to chenge based on the template? Or differently: do we even need to change out anything?

**Comment by mindreeper2420** [comment]
@michaelkleinhenz the absence of labels was done for this purpose, so you bring up a good point on the Quick Add Label. I'll talk to the team and see if that can be generalized or if it needs to be specific to the template.

**Comment by Mgranfie** [comment]
Work Item is a generic term, so wondering why it needs to be reduced down
to just "Add", add what? would be my question...
